### ISSUE TITLE
小胖子一号组装教程

### ISSUE THREAD

**Issue by Linphon** [Linphon/Share-and-show#1]
组装教程分为以下几个部分：
![default](https://user-images.githubusercontent.com/30890252/31378187-0abbca50-addd-11e7-9bb5-ef96d3f53fd9.jpg)
![2](https://user-images.githubusercontent.com/30890252/31378211-1d41401a-addd-11e7-828e-39c7662fcab4.jpg)

**Comment by Linphon** [comment]
![default](https://user-images.githubusercontent.com/30890252/31377740-a3b7cbb6-addb-11e7-984c-26b4d0123634.png)

**Comment by QGB** [comment]
where are you now？
